/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    formats: ["image/webp"],
    minimumCacheTTL: 60 * 60 * 24 * 7,
    maximumRedirects: 1,
    maximumResponseBody: 5_000_000,
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com", pathname: "/**" },
      { protocol: "https", hostname: "images.migrosone.com", pathname: "/**" },
      { protocol: "https", hostname: "encrypted-tbn0.gstatic.com", pathname: "/**" },
      { protocol: "https", hostname: "cdn.myikas.com", pathname: "/**" },
      { protocol: "https", hostname: "images.immediate.co.uk", pathname: "/**" },
      { protocol: "https", hostname: "www.yoreselbakkal.com.tr", pathname: "/**" },
      { protocol: "https", hostname: "coffeelab.com.tr", pathname: "/**" },
      { protocol: "https", hostname: "lonegoosebakery.com", pathname: "/**" },
      { protocol: "https", hostname: "assets.tmecosys.com", pathname: "/**" },
      { protocol: "https", hostname: "i.tmgrup.com.tr", pathname: "/**" },
      { protocol: "https", hostname: "panayirgourmet.com", pathname: "/**" },
      { protocol: "https", hostname: "butikpastacimm.com", pathname: "/**" },
      { protocol: "https", hostname: "i.pinimg.com", pathname: "/**" },
      { protocol: "https", hostname: "mycake.com.tr", pathname: "/**" },
      { protocol: "https", hostname: "www.bobajoy.com.tr", pathname: "/**" },
      { protocol: "https", hostname: "cdn.foodfanatic.com", pathname: "/**" },
      { protocol: "https", hostname: "lizade.com", pathname: "/**" },
      { protocol: "https", hostname: "www.drozdogan.com", pathname: "/**" },
      { protocol: "https", hostname: "static.ticimax.cloud", pathname: "/**" },
      { protocol: "https", hostname: "img3.aksam.com.tr", pathname: "/**" },
      { protocol: "https", hostname: "menu.myqrcodemenu.com", pathname: "/**" },
      { protocol: "https", hostname: "cdn.cimri.io", pathname: "/**" },
      { protocol: "https", hostname: "www.aciktimizgara.com", pathname: "/**" },
      { protocol: "https", hostname: "www.coca-cola.com", pathname: "/**" },
      { protocol: "https", hostname: "elizinn.com.tr", pathname: "/**" },
      { protocol: "https", hostname: "www.cdnaws.com", pathname: "/**" },
      { protocol: "https", hostname: "media.tarifikolay.com", pathname: "/**" },
      { protocol: "https", hostname: "www.gurmerehberi.com", pathname: "/**" },
      { protocol: "https", hostname: "moroccocoffee.com.tr", pathname: "/**" },
      { protocol: "https", hostname: "www.dogerliler.com", pathname: "/**" },
      { protocol: "https", hostname: "i.lezzet.com.tr", pathname: "/**" },
      { protocol: "https", hostname: "www.diyetkolik.com", pathname: "/**" },
      { protocol: "https", hostname: "www.kahverengicafe.com.tr", pathname: "/**" },
      { protocol: "https", hostname: "www.hisar.com.tr", pathname: "/**" },
    ],
  },
}

export default nextConfig